micronaut:
  server:
    port: -1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  info:
    enabled: true
    sensitive: false
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "localhost:8761"
#tracing:
#  zipkin:
#    enabled: true
#    http:
#      url: http://192.168.99.100:9411
#    sampler:
#      probability: 1