server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  datasources:
    default:
      url: jdbc:postgresql://127.0.0.1:5432/micronaut?ssl=false
      username: micronaut
      password: P@ssw0rd
      driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
